export const ROLES = {
  ADMIN: 'ADMIN',
  AGENT: 'AGENT',
  EMPLOYEE: 'EMPLOYEE',
  RBAC_MANAGER: 'RBAC_MANAGER',
};

export const PERMISSIONS = {
  // TICKETS
  TICKET_CREATE: 'TICKET.CREATE',
  TICKET_READ: 'TICKET.READ',
  TICKET_UPDATE: 'TICKET.UPDATE',
  TICKET_DELETE: 'TICKET.DELETE',
  TICKET_MANAGE: 'TICKET.MANAGE',

  // TICKET REPLIES
  REPLY_CREATE: 'TICKET_REPLY.CREATE',
  REPLY_READ: 'TICKET_REPLY.READ',
  REPLY_UPDATE: 'TICKET_REPLY.UPDATE',
  REPLY_DELETE: 'TICKET_REPLY.DELETE',
  REPLY_MANAGE: 'TICKET_REPLY.MANAGE',

  // METRICS
  METRICS_CREATE: 'METRICS.CREATE',
  METRICS_READ: 'METRICS.READ',
  METRICS_UPDATE: 'METRICS.UPDATE',
  METRICS_DELETE: 'METRICS.DELETE',
  METRICS_MANAGE: 'METRICS.MANAGE',

  // USERS
  USER_CREATE: 'USER.CREATE',
  USER_READ: 'USER.READ',
  USER_UPDATE: 'USER.UPDATE',
  USER_DELETE: 'USER.DELETE',
  USER_MANAGE: 'USER.MANAGE',

  // RBAC
  RBAC_CREATE: 'RBAC.CREATE',
  RBAC_READ: 'RBAC.READ',
  RBAC_UPDATE: 'RBAC.UPDATE',
  RBAC_DELETE: 'RBAC.DELETE',
  RBAC_MANAGE: 'RBAC.MANAGE',

  // AUDIT
  AUDIT_CREATE: 'AUDIT.CREATE',
  AUDIT_READ: 'AUDIT.READ',
  AUDIT_UPDATE: 'AUDIT.UPDATE',
  AUDIT_DELETE: 'AUDIT.DELETE',
  AUDIT_MANAGE: 'AUDIT.MANAGE',

  // AI
  AI_CREATE: 'AI.CREATE',
  AI_READ: 'AI.READ',
  AI_UPDATE: 'AI.UPDATE',
  AI_DELETE: 'AI.DELETE',
  AI_MANAGE: 'AI.MANAGE',

  // WILDCARD
  ALL: '*',
};
