version: '3.8'

services:
  postgres:
    image: ankane/pgvector:latest
    container_name: quickdesk-api-pgvector
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: safik
      POSTGRES_DB: quickdesk
    ports:
      - "5433:5432"
    volumes:
      - quickdesk_api_pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  quickdesk_api_pgdata:
